#pragma once

enum Morse {
	MORSE_UNIT = 250,
	MORSE_END = -1
};

#define MORSE_DIT 1, 1
#define MORSE_DAH 3, 1
#define MORSE_GAP 0, 7

static const struct { unsigned char letter; uint8_t delays[13]; } MorseMap[] =
{
	{ 'A',{ MORSE_DIT, MORSE_DAH, MORSE_END } },
	{ 'B',{ MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ 'C',{ MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ 'D',{ MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ 'E', { MORSE_DIT, MORSE_END } },
	{ 'F', { MORSE_DIT, MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ 'G', { MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ 'H', { MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ 'I', { MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ 'J', { MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_END } },
	{ 'K', { MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_END } },
	{ 'L', { MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ 'M', { MORSE_DAH, MORSE_DAH, MORSE_END } },
	{ 'N', { MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ 'O', { MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_END } },
	{ 'P', { MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ 'Q', { MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_END } },
	{ 'R', { MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ 'S', { MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ 'T', { MORSE_DAH, MORSE_END } },
	{ 'U', { MORSE_DIT, MORSE_DIT, MORSE_DAH, MORSE_END } },
	{ 'V', { MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_DAH, MORSE_END } },
	{ 'W', { MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_END } },
	{ 'X', { MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_DAH, MORSE_END } },
	{ 'Y', { MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_END } },
	{ 'Z', { MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ ' ', { MORSE_GAP, MORSE_END } }, //Gap between word, seven units

	{ '1', { MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_END } },
	{ '2', { MORSE_DIT, MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_END } },
	{ '3', { MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_END } },
	{ '4', { MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_DAH, MORSE_END } },
	{ '5', { MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ '6', { MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ '7', { MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ '8', { MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ '9', { MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ '0', { MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_END } },

	{ '.', { MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_END } },
	{ ',', { MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_END } },
	{ '?', { MORSE_DIT, MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ '!', { MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_END } },
	{ ':', { MORSE_DAH, MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_END } },
	{ ';', { MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ '(', { MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ ')', { MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_END } },
	{ '"', { MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ '@', { MORSE_DIT, MORSE_DAH, MORSE_DAH, MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_END } },
	{ '&', { MORSE_DIT, MORSE_DAH, MORSE_DIT, MORSE_DIT, MORSE_DIT, MORSE_END } },
};
